/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisador_lexico;

/**
 *
 * @author tallesventura
 */
public enum Token {
    ABRE_PARENTESES, AND, ASPAS_DUPLAS, ASPAS_SIMPLES, ATRIBUICAO, BREAK, CLASS, CONTINUE,
    DEDENT, DEF, DOIS_PONTOS, ELIF, ELSE, ERROR, OP_EXPONENCIACAO, OP_EXPONENCIACAO_IGUAL,
    FALSE, FECHA_PARENTESES, FOR, INDENT, IDENTIFICADOR, IF, IMPORT, IN, NONE, NOT, NOVA_LINHA, 
    NUMERO, OP_ADICAO, OP_DIFERENTE, OP_DIVIDIDO_IGUAL, OP_DIVISAO, OP_DIVISAO_INTEIRA, 
    OP_DIVISAO_INTEIRA_IGUAL, OP_IGUALDADE, OP_MAIOR, OP_MAIS_IGUAL, OP_MENOR, 
    OP_MENOS_IGUAL, OP_MULTIPLICACAO, OP_RESTO, OP_RESTO_IGUAL, OP_SUBTRACAO, OP_VEZES_IGUAL, 
    OR, PRINT, RANGE, RETURN, STRING, TRUE, VIRGULA, WHILE
    
}
