/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisador_lexico;

/**
 *
 * @author tallesventura
 */
public enum Token {
    ABRE_CHAVES, ABRE_COLCHETES, ABRE_PARENTESES, AND, AND_BINARIO, ASPAS_DUPLAS, ASPAS_SIMPLES, ATRIBUICAO, BREAK, CLASS,  COMPLEMENTO_DE_UM, CONTINUE,
    DEDENT, DEF, DELETE, DOIS_PONTOS, ELIF, ELSE, ERROR, EXCEPT, OP_EXPONENCIACAO, OP_EXPONENCIACAO_IGUAL,
    FALSE, FECHA_CHAVES, FECHA_COLCHETES, FECHA_PARENTESES, FOR, FROM, GLOBAL, INDENT, IDENTIFICADOR, IF, IMPORT, IN, IS, LEFT_SHIFT, NONE, NOT, NOVA_LINHA, 
    NUMERO, OP_ADICAO, OP_DIFERENTE, OP_DIVIDIDO_IGUAL, OP_DIVISAO, OP_DIVISAO_INTEIRA, 
    OP_DIVISAO_INTEIRA_IGUAL, OP_IGUALDADE, OP_MAIOR, OP_MAIOR_IGUAL, OP_MAIS_IGUAL, OP_MENOR, OP_MENOR_IGUAL,
    OP_MENOS_IGUAL, OP_MULTIPLICACAO, OP_NEGACAO, OP_RESTO, OP_RESTO_IGUAL, OP_SUBTRACAO, OP_VEZES_IGUAL, 
    OR, OR_BINARIO, OR_EXCLUSIVO_BINARIO, PONTO, PRINT, RAISE, RANGE, RETURN, RIGHT_SHIFT, STRING, TRUE, TRY, VIRGULA, WHILE
    
}
