/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JToolBar;

/**
 *
 * @author tallesventura
 */
public class MainWindowView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalView
     */
    public MainWindowView() {
        initComponents();
    }

    public JScrollPane getjScrollPaneCodigo() {
        return scrPaneEditor;
    }

    public JTable getjTableSaida() {
        return tblErros;
    }

    public JTabbedPane getJPanelArvore() {
        return jTabbedPane;
    }
    
    
    public JTable getJTableTabelaSimbolos() {
        return tblTokens;
    }

    public JButton getBtnAbrir() {
        return btnAbrir;
    }

    public JButton getBtnDesfazer() {
        return btnDesfazer;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public JButton getBtnRefazer() {
        return btnRefazer;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public JMenu getMenuArquivo() {
        return menuArquivo;
    }

    public JCheckBoxMenuItem getMenuChkBoxAnalise() {
        return menuChkBoxAnalise;
    }

    public JMenu getMenuEditar() {
        return menuEditar;
    }

    public JMenu getMenuExecutar() {
        return menuExecutar;
    }

    public JMenu getMenuFerramentas() {
        return menuFerramentas;
    }

    public JMenuItem getMenuItemAbrir() {
        return menuItemAbrir;
    }

    public JMenuItem getMenuItemAnaliseLex() {
        return menuItemAnaliseLex;
    }

    public JMenuItem getMenuItemSalvar() {
        return menuItemSalvar;
    }

    public JScrollPane getScrPaneEditor() {
        return scrPaneEditor;
    }

    public JScrollPane getScrPaneErros() {
        return scrPaneErros;
    }

    public JScrollPane getScrPaneTokens() {
        return scrPaneTokens;
    }

    public JTable getTblErros() {
        return tblErros;
    }

    public JTable getTblTokens() {
        return tblTokens;
    }
      

    public JMenuItem getBtnAvancar() {
        return btnAvancar;
    }

    public JMenuItem getBtnVoltar() {
        return btnVoltar;
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        btnAbrir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnDesfazer = new javax.swing.JButton();
        btnRefazer = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        scrPaneEditor = new javax.swing.JScrollPane();
        scrPaneErros = new javax.swing.JScrollPane();
        tblErros = new javax.swing.JTable();
        jTabbedPane = new javax.swing.JTabbedPane();
        scrPaneTokens = new javax.swing.JScrollPane();
        tblTokens = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemAbrir = new javax.swing.JMenuItem();
        menuItemSalvar = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        btnVoltar = new javax.swing.JMenuItem();
        btnAvancar = new javax.swing.JMenuItem();
        menuFerramentas = new javax.swing.JMenu();
        menuChkBoxAnalise = new javax.swing.JCheckBoxMenuItem();
        menuExecutar = new javax.swing.JMenu();
        menuItemAnaliseLex = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador Python");

        jToolBar1.setRollover(true);

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Folder-Open-icon.png"))); // NOI18N
        btnAbrir.setFocusable(false);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAbrir);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Actions-document-save-icon.png"))); // NOI18N
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSalvar);
        jToolBar1.add(jSeparator2);

        btnDesfazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Undo-icon.png"))); // NOI18N
        btnDesfazer.setFocusable(false);
        btnDesfazer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesfazer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnDesfazer);

        btnRefazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Redo-icon.png"))); // NOI18N
        btnRefazer.setFocusable(false);
        btnRefazer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefazer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnRefazer);
        jToolBar1.add(jSeparator3);

        tblErros.setBackground(new java.awt.Color(255, 153, 153));
        tblErros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblErros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblErros.setShowVerticalLines(false);
        scrPaneErros.setViewportView(tblErros);

        tblTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Linha", "Símbolo", "Token"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrPaneTokens.setViewportView(tblTokens);
        if (tblTokens.getColumnModel().getColumnCount() > 0) {
            tblTokens.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblTokens.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblTokens.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblTokens.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        jTabbedPane.addTab("Tabela de Simbolos", scrPaneTokens);

        menuArquivo.setText("Arquivo");

        menuItemAbrir.setText("Abrir");
        menuArquivo.add(menuItemAbrir);

        menuItemSalvar.setText("Salvar");
        menuArquivo.add(menuItemSalvar);

        jMenuBar1.add(menuArquivo);

        menuEditar.setText("Editar");

        btnVoltar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        btnVoltar.setText("Desfazer");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        menuEditar.add(btnVoltar);

        btnAvancar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        btnAvancar.setText("Refazer");
        menuEditar.add(btnAvancar);

        jMenuBar1.add(menuEditar);

        menuFerramentas.setText("Ferramentas");

        menuChkBoxAnalise.setSelected(true);
        menuChkBoxAnalise.setText("Ativar análise automática");
        menuFerramentas.add(menuChkBoxAnalise);

        jMenuBar1.add(menuFerramentas);

        menuExecutar.setText("Executar");

        menuItemAnaliseLex.setText("Análise Léxica");
        menuExecutar.add(menuItemAnaliseLex);

        jMenuBar1.add(menuExecutar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrPaneErros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrPaneEditor)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPaneEditor)
                    .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scrPaneErros, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JMenuItem btnAvancar;
    private javax.swing.JButton btnDesfazer;
    private javax.swing.JButton btnRefazer;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JMenuItem btnVoltar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JCheckBoxMenuItem menuChkBoxAnalise;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuExecutar;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JMenuItem menuItemAbrir;
    private javax.swing.JMenuItem menuItemAnaliseLex;
    private javax.swing.JMenuItem menuItemSalvar;
    private javax.swing.JScrollPane scrPaneEditor;
    private javax.swing.JScrollPane scrPaneErros;
    private javax.swing.JScrollPane scrPaneTokens;
    private javax.swing.JTable tblErros;
    private javax.swing.JTable tblTokens;
    // End of variables declaration//GEN-END:variables
}
